version: '3.3'
services:
  dataminer:
    image: 'datamixin/dataminer:1.0.1'
    container_name: dataminer
    restart: always
    ports:
      - ${DATAMINER_PORT:-8980}:8980
  datapilot:
    image: 'datamixin/datapilot:1.0.1'
    container_name: datapilot
    restart: always
    depends_on:
      - dataminer
    ports:
      - ${WEB_PORT:-8050}:8080
      - ${STORAGE_PORT:-8981}:8981
